### ISSUE TITLE
Question about the setup

### ISSUE THREAD

**Issue by killmasta93** [wlanut/walnuthomelab-web#1]
Hi currently i was reading your blog https://blog.walnuthomelab.com/posts/2022/may/010-swag-multiple-servers/

currently have somewhat a i dilemma, Currently i have the dns wildcard working but for extra domain i need another domain which is not in cloudflare is there a way i can add it? without moving the DNS for that domain? maybe using validation http?

Thank you

**Comment by wlanut** [comment]
> Hi currently i was reading your blog https://blog.walnuthomelab.com/posts/2022/may/010-swag-multiple-servers/
> 
> currently have somewhat a i dilemma, Currently i have the dns wildcard working but for extra domain i need another domain which is not in cloudflare is there a way i can add it? without moving the DNS for that domain? maybe using validation http?
> 
> Thank you

@killmasta93 Based on some cursory research, I am not seeing anything from SWAG users or documentation indicating it supports multiple validation methods or multiple DNS configs. In that case, if possible, I'd focus on transferring your second domain to your first one's registrar.

**Comment by killmasta93** [comment]
Thanks for the reply, what i did was create another SWAG another VM,
